// The functional requirements of Project B.A.R.I.S.T.A., per specific objective. System test cases
// (system.test.ts) point at these by number.
export const REQUIREMENTS: Record<string, { objective: string; text: string }> = {
  "FR-01": { objective: "1. QR Code Ordering", text: "The Mobile Menu shows the menu, prices, add-ons and whether the café is open." },
  "FR-02": { objective: "1. QR Code Ordering", text: "The customer customizes an item (add-ons, less or none of an ingredient) and sees the computed price." },
  "FR-03": { objective: "1. QR Code Ordering", text: "The customer orders by GCash or sends the cart to the counter; invalid quantities, unavailable items and orders while closed are refused." },
  "FR-04": { objective: "1. QR Code Ordering", text: "The customer tracks the order's queue number and status from the phone." },
  "FR-05": { objective: "2. POS and Queue", text: "The cashier takes counter orders paid in cash, with the change computed; short payments are refused." },
  "FR-06": { objective: "2. POS and Queue", text: "Senior Citizen and PWD discounts remove the VAT and take 20% off." },
  "FR-07": { objective: "2. POS and Queue", text: "GCash is paid through PayMongo; the counter does not record GCash as cash." },
  "FR-08": { objective: "2. POS and Queue", text: "Orders get sequential queue numbers per shift and move waiting → ready → picked up." },
  "FR-09": { objective: "2. POS and Queue", text: "Shifts are opened and closed with permission and password; the drawer's expected cash follows sales and cash movements." },
  "FR-10": { objective: "2. POS and Queue", text: "Voids and refunds need the password and happen once." },
  "FR-11": { objective: "2. POS and Queue", text: "Every order has a printable receipt (order slip)." },
  "FR-12": { objective: "3. Delivery", text: "Delivery orders need an address in an active zone and add the zone's fee." },
  "FR-13": { objective: "3. Delivery", text: "Riders pick up, deliver (collecting cash on delivery in full) or report a failed delivery with a reason." },
  "FR-14": { objective: "3. Delivery", text: "The cashier receives the rider's cash on delivery into the drawer." },
  "FR-15": { objective: "4. Inventory", text: "The admin manages inventory items, restocks and menu products with recipes." },
  "FR-16": { objective: "4. Inventory", text: "Sales deduct stock automatically and items run out instead of going below zero." },
  "FR-17": { objective: "4. Inventory", text: "Items at or below their low-stock level raise alerts." },
  "FR-18": { objective: "4. Inventory", text: "Staff report waste; the admin approves or writes stock off, never below zero." },
  "FR-19": { objective: "5. AI-Assisted Monitoring", text: "The admin generates AI insights for a period, only while switched on and not more than once every 5 minutes." },
  "FR-20": { objective: "6. Finance and Treasury", text: "Finance reports total sales for a valid date range." },
  "FR-21": { objective: "6. Finance and Treasury", text: "Treasury deposits and withdrawals need the password and never take an account below zero." },
  "FR-22": { objective: "6. Finance and Treasury", text: "Expenses are recorded with an amount, category and source of funds." },
  "FR-23": { objective: "7. User Management", text: "The admin adds, edits, deactivates and sets the role of employee accounts." },
  "FR-24": { objective: "7. User Management", text: "Customers create accounts with consent and a unique username." },
  "FR-25": { objective: "8. Security", text: "Signing in on a new device needs the code emailed to the account." },
  "FR-26": { objective: "8. Security", text: "Each role can only use its own functions; requests without a valid session are refused." },
  "FR-27": { objective: "8. Security", text: "Signing out ends the session on the server." },
  "FR-28": { objective: "9. Notifications", text: "The admin's notifications show stock, waste, delivery and cash-drawer problems." },
  "FR-29": { objective: "9. Notifications", text: "The Queue Screen and the customer's phone show order status changes." },
  "FR-30": { objective: "10. Loyalty", text: "Linked orders earn 1 star each, at most 5 a day." },
  "FR-31": { objective: "10. Loyalty", text: "A reward is redeemed only with enough stars and the customer's confirmation." },
};
